 
version: '3'
services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://master:password@db:5432/pwc
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: master
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pwc
      POSTGRES_USER: master
      POSTGRES_PASSWORD: password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8090:8080"
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - postgrest
