name: Publish PWC Beyond to Itch.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }} # Needs to be added through github
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IS_MAIN: ${{ contains(github.ref, 'main') }}
  PROJECT_NAME: "PWC Beyond"

jobs:
  CleanArtifacts:
    # This job clears out the previous artifacts made so you don't run out of space in your github account
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1hr

  GenerateGodotExports:
    needs: CleanArtifacts # wait for artifacts to clean before making a new one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download + Authorize Godot
        run: |
          curl -sL -o godot.zip https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_linux.x86_64.zip
          unzip godot.zip
          mv Godot_v4.1.1-stable_linux.x86_64 godot
          chmod +x godot

      - name: Prepare Export Templates
        run: |
          curl -sL -o export_templates.zip https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_export_templates.tpz
          unzip export_templates.zip
          mkdir -p ~/.local/share/godot/export_templates/4.1.1.stable
          mv ./templates/* ~/.local/share/godot/export_templates/4.1.1.stable

      - name: Godot Export Windows Desktop
        run: |
          mkdir -p ./build
          ./godot --headless --path ./ --export-release "Windows Desktop" ./build/pwcbeyond.exe

      - name: Godot Export HTML5/Web
        run: |
          mkdir -p ./build/pwcbeyond-html
          ./godot --headless --path ./ --export-release "pwcbeyond-html" ./build/pwcbeyond-html/index.html
          zip -mjr ./build/pwcbeyond.zip ./build/pwcbeyond-html/*

      - name: Godot Export Linux/X11
        run: |
          mkdir -p ./build
          ./godot --headless --path ./ --export-release "Linux/X11" ./build/pwcbeyond

      - name: Upload Godot Exports as workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pwcbeyond-builds
          path: ./build

  GithubRelease:
    needs: GenerateGodotExports
    if: ${{ contains(github.ref, 'main') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Version
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Tag
        if: ${{ !steps.tag_version.outputs.new_tag }}
        run: exit 1

      - name: Retrieve Godot Exports
        uses: actions/download-artifact@v3
        with:
          name: pwcbeyond-builds
          path: ./pwcbeyond

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: PWCBeyond ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Upload Release Windows Godot Export
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pwcbeyond/pwcbeyond.exe
          asset_name: pwcbeyond-windows.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Linux Godot Export
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pwcbeyond/pwcbeyond
          asset_name: pwcbeyond-linux
          asset_content_type: application/octet-stream

      - name: Upload Release Web/HTML5 Godot Export
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pwcbeyond/pwcbeyond.zip
          asset_name: pwcbeyond-html
          asset_content_type: application/zip

      - uses: frdrwrt/write-to-file@v1.3
        with:
          filepath: ./VERSION.txt
          content: ${{ steps.tag_version.outputs.new_version }}
          mode: 0655

      - uses: actions/upload-artifact@v2
        with:
          name: VERSION
          path: ./VERSION.txt

  ItchIOPublish:
    needs: GithubRelease
    if: ${{ contains(github.ref, 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Godot Exports
        uses: actions/download-artifact@v3
        with:
          name: pwcbeyond-builds
          path: ./pwcbeyond

      - name: Download + Authorize Butler
        run: |
          curl -sL -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Login To Butler
        run: ./butler login

      - name: Butler upload binary builds
        run: |
          ./butler push .pwcbeyond/pwcbeyond:linux
          ./butler push .pwcbeyond/pwcbeyond.exe:windows

      - name: Butler upload HTML5/Web build
        run: |
          ./butler push .pwcbeyond/pwcbeyond:linux
          ./butler push .pwcbeyond/pwcbeyond.exe:windows

  Cleanup:
    needs: ItchIOPublish
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: VERSION
